global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: django
    metrics_path: /metrics
    static_configs:
      - targets:
        - app1:8000

  - job_name: consumer
    metrics_path: /metrics
    static_configs:
      - targets:
        - app2:8080
