global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: django
    metrics_path: /metrics
    static_configs:
      - targets:
        - app1:8000

  - job_name: consumer
    metrics_path: /metrics
    static_configs:
      - targets:
        - app2:8080

  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: pushgateway
    metrics_path: /metrics
    static_configs:
      - targets:
        - pushgateway:9091


  - job_name: node-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
        - node-exporter:9100
